# .scrutinizer.yml

build:

    dependencies:
        before:
            - rm composer.lock

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'

    nodes:

        php83:
            environment:
                php: 8.3

        php84:
            environment:
                php: 8.4

        php85:
            environment:
                php: 8.5


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*

