# .scrutinizer.yml
build:

    dependencies:
        before:
            - rm composer.lock

    # ---------------------------------------------------------
    # This makes no sense here as it will break tests with hhvm
    # ---------------------------------------------------------

    # tests:
    #     override:
    #         -
    #             command: 'vendor/bin/phpunit --coverage-clover=coverage'
    #             coverage:
    #                 file: 'coverage'
    #                 format: 'php-clover'

    nodes:
        # Common versions: 5.4, 5.5, 5.6, 7.1 or hhvm
        php70:
            environment:
                php: 7.0.20
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php71:
            environment:
                php: 7.1

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php72:
            environment:
                php: 7.2

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        php56:
            environment:
                php: 5.6

            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=coverage'
                        coverage:
                            file: 'coverage'
                            format: 'php-clover'

        hhvm:
            environment:
                php: hhvm


checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*
