# .scrutinizer.yml

build:
    dependencies:
        before:
            - rm -f composer.lock

    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'

    nodes:
        php84:
            environment:
                php: 8.4

checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*

