# .travis.yml


language: php

php:
  - "8.3"
  - "8.4"
  - "8.5"

env:

before_script:
  - rm composer.lock
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp phpunit.xml.dist phpunit.xml

script:
  - composer test

after_script:

